site_name: 创作与游戏操作系统自由运动 Wiki(Fuck MS Wiki)
site_url: https://fuckms.ne0w0r1d.top
repo_url: https://github.com/Ne0W0r1d/FreedomGameCreatorWiki
repo_name: Ne0W0r1d/FreedomGameCreatorWiki
theme:
  name: material
  language: zh
  features:
    - palette.toggle
    - content.code.copy
  logo: images/icon.jpg

  palette:
    # 浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Deep♂Dark♂Fantasy♂

    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: \O/
  favicon: images/icon.jpg
  icon:
    repo: material/source-repository
    # logo: images/icon.jpg
